version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.7.3-stretch
        steps:
            - checkout

#            - run:
#                name: Check requirements.txt and doc/requirements.txt syncing
#                # doc/requirements.txt must be a perfect copy of requirements.txt
#                # with a single line "  - eztracks~=0.X" added in the pip section
#                command: diff <(grep -v '^  - autoengage~=0.1.0$' requirements.txt) <(cat requirements.txt)

            # restore cache from last build. Unless __init__.py has changed since then
            - restore_cache:
                keys:
                  - data-cache-0-{{ checksum "./autoengage/__init__.py" }}

            # Also restore pip cache to speed up installations
            - restore_cache:
                keys:
                  - pip-cache-0-{{ checksum "./requirements.txt" }}

            - run:
                name: Setup Python environment via Pip/Setup
                # ... but use latest version of autoengage
                command: |
                  python -m venv .venv
                  source activate .venv/bin/activate
                  make inplace

            - run:
                name: Run unit and integration tests
                command: |
                  source activate testenv
                  make check
                  pytest ./tests/
#                  $HOME/.local/bin/coverage run -m pytest ./tests
#                  $HOME/.local/bin/coverage report
#                  $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser

            # Store pip cache
            - save_cache:
                key: pip-cache-0-{{ checksum "./requirements.txt" }}
                paths:
                  - ~/.cache/pip

            - add_ssh_keys:
                fingerprints:
                  - "fd:39:54:fd:e0:85:47:67:c3:ef:e8:8d:99:30:f0:79"

            - deploy:
                name: github pages deployment
                command: |
                  source activate testenv
                  if [ "${CIRCLE_BRANCH}" == "maint/0.3" ]; then
                    echo "Deploying stable docs for ${CIRCLE_BRANCH}.";
                    git config --global user.email "circle@adam2392@gmail.com";
                    git config --global user.name "Circle Ci";
                    cd doc;
                    make install;
                  else
                    echo "No deployment (build: ${CIRCLE_BRANCH}).";
                  fi
